[package]
name = "stock_cli_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
yahoo_finance_api = "2.4.0"
